name: Build and Push

#trigger
on:
- push

jobs:
  #name of your job
  myjob: 
    #runner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        # scan-type: 'fs'
        # scan-ref: '.'
        # trivy-config: trivy.yaml
        # severity: 'CRITICAL,HIGH'
        # format: 'sarif'
        # output: 'trivy-report.sarif'
        # format: 'json'
        # output: 'trivy-report.json'
        scan-type: 'config'
        ignore-unfixed: true
        hide-progress: true
        format: table
        vuln-type: 'os,library'
        output: 'trivy-report.txt'
        severity: 'CRITICAL,HIGH'

    # - name: Convert to table
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: convert
    #     vuln-type: ""
    #     image-ref: trivy-report.json
    #     format: table
    #     output: 'trivy-report.txt'
    #     severity: 'CRITICAL,HIGH'

    - name: Upload trivy report as a Github artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: 'trivy-report.txt'
        retention-days: 20 # 90 is the default

    # - name: Upload Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #       sarif_file: 'trivy-report.sarif'
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
        SLACK_TITLE: Scan failed - XiaTian
        SLACK_USERNAME: DipSA58 CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_FILE_UPLOAD: 'trivy-report.txt'
        initial_comment: 'Scan report by Xia Tian'

    # - name: Slack Notification
    #   uses: MeilCli/slack-upload-file@v4
    #   with:
    #     content: 'file content'
    #     file_type: 'text'
    #     title: Scan failed - XiaTian
    #     slack_token: ${{ secrets.SLACK_TOKEN }}
    #     channel_id: ${{ secrets.SLACK_CHANNEL }}
    #     file_path: 'trivy-report.sarif'
    #     initial_comment: 'Scan report by Xia Tian'
        