name: Build and Push

#trigger
on:
- push

jobs:
  #name of your job
  myjob: 
    #runner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml

    - name: Save Trivy Scan Result
      run: echo "${{ steps.trivy-scan.outputs.scan-result }}" | base64 -d > trivy-report.txt
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure' # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
        SLACK_TITLE: Scan failed - XiaTian
        SLACK_USERNAME: DipSA58 CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_FILE_UPLOAD: trivy-report.txt
        initial_comment: 'Scan report by Xia Tian'

    # - name: Upoad trivy scan report
    #   uses: MeilCli/slack-upload-file@v4
    #   with:
    #     slack_token: ${{ secrets.SLACK_TOKEN }}
    #     channel_id: ${{ secrets.SLACK_CHANNEL }}
    #     content: '${{ steps.trivy-scan.outputs.scan-result }}'
    #     file_type: 'text'
    #     file_name: 'file-report.txt'
    #     title: 'Trivy Scan Report'
    #     initial_comment: 'Scan report by Xia Tian'
        # thread_ts: 'option'
        
