name: Build and Push

#trigger
on:
- push

jobs:
  #name of your job
  myjob: 
    #runner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: 329946325/CA:${{ github.sha }}
        build-args: |
            SOME_ARG: some_value
   
    - name: Sign Docker Image
      run: echo "TEST SIGN"


    - name: Run Trivy vulnerability scanner in fs mode
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'      
        # scan-type: 'config'
        # ignore-unfixed: true
        # hide-progress: true
        # vuln-type: 'os,library'
        # format: 'sarif'
        # output: 'trivy-report.sarif'
        format: 'table'
        output: './trivy-report.json'
        # ignore-unfixed: true
        # severity: 'CRITICAL,HIGH'

    # - name: Convert to table
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: convert
    #     vuln-type: ""
    #     image-ref: trivy-report.json
    #     format: table
    #     output: 'trivy-report.txt'
    #     severity: 'CRITICAL,HIGH'

    # - name: Debug
    #   run: |
    #     echo "Listing files in directory..."
    #     ls -l
    #     echo "Showing content of trivy report..."
    #     cat ./trivy-report.json

    - name: Upload trivy report as a Github artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: './trivy-report.json'
        retention-days: 20 # 90 is the default

    # - name: Upload Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #       sarif_file: 'trivy-report.sarif'
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
        SLACK_TITLE: Scan failed - XiaTian
        SLACK_USERNAME: DipSA58 CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_FILE_UPLOAD: './trivy-report.json'
        initial_comment: 'Scan report by Xia Tian'

    # - name: Slack Notification
    #   uses: MeilCli/slack-upload-file@v4
    #   with:
    #     content: 'file content'
    #     file_type: 'text'
    #     title: Scan failed - XiaTian
    #     slack_token: ${{ secrets.SLACK_TOKEN }}
    #     channel_id: ${{ secrets.SLACK_CHANNEL }}
    #     file_path: 'trivy-report.sarif'
    #     initial_comment: 'Scan report by Xia Tian'


        