name: Build and Push

#trigger
on:
- push

jobs:
  #name of your job
  myjob: 
    #runner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml

    - name: Save Trivy Scan Result
      run: echo "${{ steps.trivy-scan.outputs.scan-results }}" > trivy_scan_result.txt
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'success' # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
        SLACK_TITLE: Scan failed - XiaTian
        SLACK_USERNAME: DipSA58 CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  
      with:
        attachment: trivy_scan_result.txt
