name: my workflow

#trigger
on:
- push

jobs:
  #name of your job
  myjob: 
    #runner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.19.0
